wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719879171
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.11.9
      5: 0.17.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
